### ISSUE TITLE
Match Title Filename

### ISSUE THREAD

**Issue by Medullitus** [stroiman/obsidian-title-sync#2]
Hey. Thx for the plugin. Can you please add a feature to match titlename with the actual name of the file? Thx

**Comment by stroiman** [comment]
Hi, Thanks for liking it :D

I was actually planning on improving the plugin in one of the coming days, primarily make it compatible with mobile devices, so I could consider this too.

But what exact use case you want? Just a command you can run for the case that the H1 title in the markdown has come out of sync with the filename?

That rarely happens to me, as the markdown is normally generated by a template. In the rare case that they are out of sync, I just press F2 (for renaming a file), which highlights the file name, which I can copy, and paste into the H1 title.

But if it's just the matter of a command on the command palette to do this, that should not be a problem to add.

**Comment by Medullitus** [comment]
Hello,

Thank you very much for your response. I have migrated my notes from Joplin to Obsidian. However, unfortunately, the names of my notes do not match the titles. For example:

Note name: BATTLEFIELD 1 FAILS & Epic Moments! _1 (BF1 Funny

Title: BATTLEFIELD 1 FAILS & Epic Moments! #1 (BF1 Funny Moments Beta Gameplay Montage) - YouTube

The reason the title doesn't reflect in the note name is because it contains unsupported characters like & and #. I use a plugin called "Smart Rename" to automatically eliminate these characters and paste the title into the note name. But considering I have thousands of notes, doing this manually is very difficult. What I need is for the plugin to do this automatically. Such a solution would benefit users like me. I hope I have explained myself clearly

**Comment by stroiman** [comment]
I'm a little unsure, what you want, when you say "notename" and "title". I assume by "note name" you refer to the filename? and "Title", you refer to the H1 element in the markdown "# Title"

```
# Title in markdown
```

And from what I understand, you have in the markdown contents, characters that are invalid file names?

But the contents in the markdown also appears to be what is the desired display when actually opening a file? Don't you want the text on the screen to actually _show_ "Epic Moments! #1"?

The philosophy of this plugin is that it is _desirable_, but not essential, that the title in markdown and filename are identical. There are plenty of cases where I want to use `:`, `/`, `&`, etc in the title in markdown, so in these cases, the filenames are just something close, not identical. That is also the reason this plugin doesn't update the H1 title, if it's not an identical match.

But I don't mind seeing if I can make a command, that forcibly updates the H1 to match filename - I don't think it should be that big a deal, it's simply ignoring the check if they already match.

**Comment by Medullitus** [comment]
I would like to explain it to you through screenshots. I want to apply this process automatically to all notes.

![1](https://github.com/stroiman/obsidian-title-sync/assets/52373851/9f81183d-1dba-4f97-ab55-4d9dd1fa8c51)
![2](https://github.com/stroiman/obsidian-title-sync/assets/52373851/338c0d95-1aa0-40f7-9c55-b1b6d5689cd7)
![3](https://github.com/stroiman/obsidian-title-sync/assets/52373851/606be5e4-2465-42a5-a5f1-9de8ef563f14)

**Comment by stroiman** [comment]
Ok, I understand what you want, and I am not going to support that.

I have multiple times explicitly mentioned, and that's what the readme file specifies also, that I update the H1 heading in the markdown. Your example does not have an H1 - you are talking about a title property in frontmatter. This plugin does not support, and I do not have any plans of supporting that either.

Sorry to disappoint. 

This example should explain, what I mean

<img width="996" alt="image" src="https://github.com/stroiman/obsidian-title-sync/assets/237227/81c94d5a-6c24-4c02-9533-bec6e4ef0e26">

**Comment by Medullitus** [comment]
It's disappointing to hear that you won't support this. It could have been a feature that set your plugin apart. If your decision is final, I guess there's nothing more to be done. Thank you for your quick responses and attention.
